baseURL: https://blog.psi59.com
languageCode: ko-kr
title: "Sangil's Blog"
theme: "PaperMod"
googleAnalytics: G-MMTYEB98J6
taxonomies:
      category: categories
      tag: tags
markup:
  goldmark:
      renderer:
          unsafe: true
params:
  env: production
  author: "박상일"
  defaultTheme: "light"
  disableThemeToggle: "true"  
  ShowReadingTime: true 
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  cover:
    responsiveImages: true
  comments: true
  homeInfoParams:
    Title: "Sangil's Blog"
    Content: >
        여행과 음악을 좋아하는 Go backend 개발자입니다.

  socialIcons:
    - name: github
      url: "https://github.com/psi59"
    - name: email
      url: "mailto:tkddlf59@gmail.com"
    - name: RSS
      url: "index.xml"
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20